// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLgRBvwfpsxqTa0kgwMRJycGGN8ci1-I',
    appId: '1:1001868973210:web:b7a57e43a54ae1105dbb23',
    messagingSenderId: '1001868973210',
    projectId: 'foxtconnect-2023',
    authDomain: 'foxtconnect-2023.firebaseapp.com',
    storageBucket: 'foxtconnect-2023.firebasestorage.app',
    measurementId: 'G-F0ZSM0972L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6TcEDRCE6S2HpUeoo5-NcWjT51QuZcw',
    appId: '1:1001868973210:android:61b170996e9bbd535dbb23',
    messagingSenderId: '1001868973210',
    projectId: 'foxtconnect-2023',
    storageBucket: 'foxtconnect-2023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9x-V_pRUutj8WqTOXBa_wXowT8RlX63I',
    appId: '1:1001868973210:ios:8f0add0b9ca214755dbb23',
    messagingSenderId: '1001868973210',
    projectId: 'foxtconnect-2023',
    storageBucket: 'foxtconnect-2023.firebasestorage.app',
    iosBundleId: 'com.example.foxConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9x-V_pRUutj8WqTOXBa_wXowT8RlX63I',
    appId: '1:1001868973210:ios:8f0add0b9ca214755dbb23',
    messagingSenderId: '1001868973210',
    projectId: 'foxtconnect-2023',
    storageBucket: 'foxtconnect-2023.firebasestorage.app',
    iosBundleId: 'com.example.foxConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwLgRBvwfpsxqTa0kgwMRJycGGN8ci1-I',
    appId: '1:1001868973210:web:5456fb6d297d1b255dbb23',
    messagingSenderId: '1001868973210',
    projectId: 'foxtconnect-2023',
    authDomain: 'foxtconnect-2023.firebaseapp.com',
    storageBucket: 'foxtconnect-2023.firebasestorage.app',
    measurementId: 'G-NB6P7RTD2L',
  );
}
